# Existing
FLASK_APP=run.py
FLASK_ENV=development
SECRET_KEY=your_secret_key_here
SQLALCHEMY_DATABASE_URI=sqlite:///techtrack.db
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0

# NEW SMTP SETTINGS
MAIL_SERVER='smtp.gmail.com'
MAIL_PORT='587'
MAIL_USE_TLS='True'
MAIL_USERNAME='service.pulse.erp@gmail.com'
MAIL_PASSWORD='wjhmlneucqjadxhf'
MAIL_DEFAULT_SENDER='service.pulse.erp@gmail.com'
DB_BACKUP_LAST='2025-09-11T13:42:25'
DB_BACKUP_LAST_STATUS='SUCCESS'
DB_BACKUP_ENABLED='True'
DB_BACKUP_TIME='02:00'
DB_BACKUP_KEEP_DAYS='7'
DB_BACKUP_DIR='C:/backups'
GDRIVE_SA_JSON='D:\Biztra\servicepulse\app\uploads\keys\mfi-backup-2313fae63742.json'
SMB_ENABLED='False'
SMB_SHARE=''
SMB_USER=''
GDRIVE_ENABLED='False'
GDRIVE_FOLDER_ID='1aBqPYKMQ55iGr6jGPVsGohzK-O4FCI6V'
DB_BACKUP_LAST_CLOUD='2025-08-15T21:26:05'
DB_BACKUP_LAST_CLOUD_STATUS='FAIL: <HttpError 403 when requesting https://www.googleapis.com/upload/drive/v3/files?fields=id%2Cname%2Cparents&supportsAllDrives=true&alt=json&uploadType=multipart returned "Service Accounts do not have storage quota. Leverage shared drives (https://developers.google.com/workspace/drive/api/guides/about-shareddrives), or use OAuth delegation (http://support.google.com/a/answer/7281227) instead.". Details: "[{\'message\': \'Service Accounts do not have storage quota. Leverage shared drives (https://developers.google.com/workspace/drive/api/guides/about-shareddrives), or use OAuth delegation (http://support.google.com/a/answer/7281227) instead.\', \'domain\': \'usageLimits\', \'reason\': \'storageQuotaExceeded\'}]">'
BRAND_COMPANY_NAME='MFI MANAGED DOCUMENT SOLUTIONS LTD'
BRAND_DOC_TITLE_FORMAT='{company_name} ({doc_type})'
BRAND_DOC_TYPE_UPPER='True'
BRAND_LOGO_LIGHT=''
BRAND_LOGO_DARK=''
BRAND_LOGO_ICON=''
BRAND_WATERMARK=''
LOG_CLEAN_LAST='2025-08-19T10:59:46'
LOG_CLEAN_LAST_STATUS='SUCCESS: deleted 225115'
LOG_RETENTION_ENABLED='True'
LOG_RETENTION_DAYS='30'
LOG_CLEAN_TIME='03:10'
MAIL_USE_SSL='False'
